backend:
  name: git-gateway
  branch: main
collections:
  - name: blog
    label: blog
    folder: src/content/posts
    create: true
    fields:
      - name: slug
        hint: "Last part of URL after 'blog/'"
      - name: title
      - name: publication_date
        label: Publication Date
        widget: datetime
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07 
      - name: body
        widget: markdown
  - name: events
    label: events
    folder: src/content/events
    create: true
    fields:
      - name: slug
        hint: "Last part of URL after 'blog/'"
      - name: title
      - name: publication_date
        label: Publication Date
        widget: datetime
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07 
      - name: body
        widget: markdown
      - name: facebook_link
        hint: Url to Facebook-event
      - name: image
        widget: image
  - name: tools
    label: tools
    file: src/content/tools.md

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://sykkelkjokken.no
display_url: https://sykkelkjokken.no
logo_url: ../title.png
