backend:
  name: git-gateway
  branch: i18n
collections:
  - name: "settings"
    label: "Settings"
    i18n: true
    files:
      - label: "Header message"
        name: header_message
        file: "src/config/header_message.json"
        i18n: true
        fields:
          - name: message
            widget: text
            i18n: true
      - label: "Memberships"
        name: memberships
        file: "src/config/memberships.json"
        i18n: false
        fields:
          - name: memberships
            widget: list
            collapsed: false
            fields:
              - { label: "Name", name: "name", widget: string }
              - {
                  label: "Reduced",
                  name: "reduced",
                  widget: boolean,
                  default: false,
                  required: false,
                  hint: "This is a reduced price membership for students etc.",
                }
              - { label: "Price", name: "price", widget: number }
  - name: "Resources"
    label: "Resources"
    i18n:
      structure: multiple_files
    folder: src/content/pages/resources
    fields:
      - name: body
        widget: markdown
        i18n: true
  - name: "Tools"
    label: "Tools"
    folder: src/content/pages/tools
    i18n:
      structure: multiple_files
    fields:
      - name: body
        widget: markdown
        i18n: true
  # - name: blog
  #   label: Blog
  #   folder: src/content/posts
  #   create: true
  #   fields:
  #     - name: slug
  #       hint: "Last part of URL after 'blog/'"
  #     - name: title
  #     - name: publication_date
  #       label: Publication Date
  #       widget: datetime
  #       date_format: "DD.MM.YYYY"
  #       time_format: "HH:mm"
  #     - name: body
  #       widget: markdown

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://sykkelkjokken.no
display_url: https://sykkelkjokken.no
logo_url: ../title.png

i18n:
  structure: single_file
  locales: ["en", "no"]
