backend:
  name: git-gateway
  branch: main
collections:
  - name: blog
    label: blog
    folder: src/content/posts
    create: true
    fields:
      - name: title
      - name: preamble
        hint: "Lead paragraph - Såkalla ingress på norsk"
      - name: slug
        hint: "Last part of URL after 'blog/'"
      - name: publication_date
        widget: datetime
      - name: body
        widget: markdown
media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://dev.sykkelkjokken.no
display_url: https://dev.sykkelkjokken.no
logo_url: ../logo.svg