backend:
  name: git-gateway
  branch: main
collections:
  - name: "settings"
    label: "Settings"
    files:
      - label: "Header message"
        name: header_message
        file: "src/config/header_message.json"
        fields:
          - name: message
            widget: text
      - label: "Memberships"
        name: memberships
        file: "src/config/memberships.json"
        fields:
          - name: memberships
            widget: list
            collapsed: false
            fields:
              - { label: "Name", name: "name", widget: string }
              - {
                  label: "Id",
                  name: "id",
                  widget: string,
                  hint: "For internal use",
                }
              - {
                  label: "Reduced",
                  name: "reduced",
                  widget: boolean,
                  default: false,
                  required: false,
                  hint: "This is a reduced price membership for students etc.",
                }
              - { label: "Price", name: "price", widget: number }
              - {
                  label: "Start Date",
                  name: "start_date",
                  widget: datetime,
                  date_format: "DD.MM.YYYY",
                  time_format: false,
                }
              - {
                  label: "End Date",
                  name: "end_date",
                  widget: datetime,
                  date_format: "DD.MM.YYYY",
                  time_format: false,
                }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Tools page"
        name: "tools"
        file: "src/routes/tools/+page.md"
        fields:
          - name: body
            widget: markdown
      - label: "Resources page"
        name: "resources"
        file: "src/routes/resources/+page.md"
        fields:
          - name: body
            widget: markdown
  - name: blog
    label: Blog
    folder: src/content/posts
    create: true
    fields:
      - name: slug
        hint: "Last part of URL after 'blog/'"
      - name: title
      - name: publication_date
        label: Publication Date
        widget: datetime
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
      - name: body
        widget: markdown

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://sykkelkjokken.no
display_url: https://sykkelkjokken.no
logo_url: ../title.png
