backend:
  name: git-gateway
  branch: main
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Header message"
        name: header_message
        file: "src/routes/header_message.txt"
        fields:
          - name: message
            widget: text
      - label: "Tools page"
        name: "tools"
        file: "src/routes/tools/+page.md"
        fields:
          - name: body
            widget: markdown
      - label: "Resources page"
        name: "resources"
        file: "src/routes/resources/+page.md"
        fields:
          - name: body
            widget: markdown
  - name: blog
    label: Blog
    folder: src/content/posts
    create: true
    fields:
      - name: slug
        hint: "Last part of URL after 'blog/'"
      - name: title
      - name: publication_date
        label: Publication Date
        widget: datetime
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07
      - name: body
        widget: markdown

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://sykkelkjokken.no
display_url: https://sykkelkjokken.no
logo_url: ../title.png
